### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Reem-lab** [zhadier/Rent-A-Movie#26]
## Highlights to say 👍 
 - You have a clean and readable code
 - Great job so far 💥
 -  No issues to say

<img src="https://media4.giphy.com/media/26gsobowozGM9umBi/giphy.gif"/>

**Comment by gabyse1** [comment]
### Hi @zhadier 
First of all congratulations on your good job!!!
Your code is DRY and KISS.
I don't have additional suggestions.
Happy codding.

**Comment by zhadier** [comment]
# Hello fellow Micronauts and Friends :high_brightness: 
#### Thank you so much for the kind words :last_quarter_moon_with_face:, it means a lot coming from amazing developers like you :smiley: :rice_cracker:
